"""

Revision ID: 40270cfe7395
Revises: 
Create Date: 2023-07-29 09:24:58.048557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40270cfe7395'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('title', sa.VARCHAR(length=125), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.VARCHAR(length=125), nullable=True),
    sa.PrimaryKeyConstraint('title')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('active_book', sa.VARCHAR(length=125), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('contents_page', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book', sa.VARCHAR(length=125), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarks')
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###
